import { LLMClient, LLMMessage } from './types';
import { Chunk } from '../ingestion/types';
import { Context } from '../context/types';

export class MockLLM implements LLMClient {
  async generate(messages: LLMMessage[]): Promise<string> {
    // Mock implementation that creates a response based on the last user message
    const lastUserMessage = messages
      .slice()
      .reverse()
      .find(msg => msg.role === 'user');
    
    if (!lastUserMessage) {
      return "I'm a mock LLM. No user message found to respond to.";
    }

    // Simple response generation based on keywords
    const content = lastUserMessage.content.toLowerCase();
    
    if (content.includes('hello') || content.includes('hi') || content.includes('hey')) {
      return "Hello! I'm your mock AI assistant. How can I help you today?";
    } else if (content.includes('thank')) {
      return "You're welcome! Let me know if you need anything else.";
    } else if (content.includes('help')) {
      return "I'm here to help! You can ask me questions about your knowledge sources or request text edits.";
    } else {
      return `This is a mock response to: "${lastUserMessage.content}". In a real implementation, this would be generated by an LLM.`;
    }
  }

  async answer(question: string, retrievedChunks: Chunk[], context: Context): Promise<string> {
    if (retrievedChunks.length === 0) {
      return "In strict mode: No relevant information found in the provided sources to answer this question.";
    }

    // Combine all chunk text to analyze
    const fullText = retrievedChunks.map(chunk => chunk.text).join(' ');
    
    // For word-specific questions, extract and return actual information
    const questionLower = question.toLowerCase();
    const words = fullText.split(/\s+/).filter(word => word.length > 0);
    
    if (questionLower.includes('first word') || (questionLower.includes('first') && questionLower.includes('word'))) {
      if (words.length > 0) {
        return `The first word in the document is "${words[0]}".`;
      } else {
        return "The document appears to be empty.";
      }
    } else if (questionLower.includes('second word') || (questionLower.includes('second') && questionLower.includes('word'))) {
      if (words.length > 1) {
        return `The second word in the document is "${words[1]}".`;
      } else {
        return `The document has fewer than 2 words. It contains ${words.length} word(s).`;
      }
    } else if (questionLower.includes('third word') || (questionLower.includes('third') && questionLower.includes('word'))) {
      if (words.length > 2) {
        return `The third word in the document is "${words[2]}".`;
      } else {
        return `The document has fewer than 3 words. It contains ${words.length} word(s).`;
      }
    } else if (questionLower.includes('word count') || questionLower.includes('many words') || questionLower.includes('number of words') ||
               (questionLower.includes('how many') && questionLower.includes('word'))) {
      return `The document contains approximately ${words.length} words.`;
    } else if (questionLower.includes('character count') || questionLower.includes('many characters') || questionLower.includes('number of characters') ||
               (questionLower.includes('how many') && questionLower.includes('character'))) {
      return `The document contains approximately ${fullText.length} characters.`;
    } else if (questionLower.includes('fifth word') || (questionLower.includes('fifth') && questionLower.includes('word'))) {
      if (words.length > 4) {
        return `The fifth word in the document is "${words[4]}".`;
      } else {
        return `The document has fewer than 5 words. It contains ${words.length} word(s).`;
      }
    } else if (questionLower.includes('15-th word') || questionLower.includes('15th word') ||
               (questionLower.includes('15') && questionLower.includes('word'))) {
      if (words.length > 14) {
        return `The 15th word in the document is "${words[14]}".`;
      } else {
        return `The document has fewer than 15 words. It contains ${words.length} word(s).`;
      }
    } else if (questionLower.includes('what is') && (questionLower.includes('document') || questionLower.includes('content') || questionLower.includes('about'))) {
      // Extract main topics from the content
      const textLower = fullText.toLowerCase();
      const topics = [];
      
      if (textLower.includes('artificial intelligence') || textLower.includes('ai')) {
        topics.push('Artificial Intelligence');
      }
      if (textLower.includes('machine learning')) {
        topics.push('Machine Learning');
      }
      if (textLower.includes('neural network') || textLower.includes('neural networks')) {
        topics.push('Neural Networks');
      }
      if (textLower.includes('natural language processing') || textLower.includes('nlp')) {
        topics.push('Natural Language Processing');
      }
      if (textLower.includes('deep learning')) {
        topics.push('Deep Learning');
      }
      if (textLower.includes('transform')) {
        topics.push('Industry Transformation');
      }
      
      const topicStr = topics.length > 0 ? topics.join(', ') : 'various AI and technology topics';
      return `This document is about: ${topicStr}. It discusses how these technologies are transforming industries and their applications.`;
    } else {
      // For other questions, provide a response based on the content
      // In a real implementation with DeepSeek, the LLM would naturally understand and respond to the question
      const relevantContent = retrievedChunks.slice(0, 2).map(chunk => chunk.text.substring(0, 200) + '...').join('\n\n');
      
      return `Based on the provided sources:\n\n${relevantContent}\n\nAnswer: In a real implementation with an LLM like DeepSeek, the AI would analyze the question "${question}" and generate a comprehensive response based on the relevant information from the documents.`;
    }
  }


  async edit(inputText: string, instruction: string, retrievedChunks: Chunk[], context: Context): Promise<string> {
    // Apply basic transformations based on the instruction
    let resultText = inputText;
    const instructionLower = instruction.toLowerCase();
    
    if (instructionLower.includes('shorter') || instructionLower.includes('summarize') || instructionLower.includes('reduce')) {
      // Simple summarization by taking first and last parts
      const words = inputText.split(/\s+/);
      if (words.length > 10) {
        resultText = words.slice(0, Math.min(10, Math.floor(words.length/2))).join(' ') + ' [...] ' + words.slice(-Math.min(5, Math.ceil(words.length/2))).join(' ');
      } else {
        resultText = words.slice(0, Math.min(5, words.length)).join(' ') + ' [...]';
      }
    } else if (instructionLower.includes('longer') || instructionLower.includes('expand')) {
      resultText = inputText + ' [expanded with additional details based on knowledge sources...]';
    } else if (instructionLower.includes('rewrite') || instructionLower.includes('rephrase')) {
      resultText = '[Rewritten]: ' + inputText.split(/\s+/).reverse().join(' ') + ' [end rewrite]';
    } else if (instructionLower.includes('fix') || instructionLower.includes('grammar') || instructionLower.includes('correct')) {
      resultText = '[Grammar checked and corrected]: ' + inputText + ' [corrections applied based on knowledge sources]';
    } else {
      // For other instructions, apply basic transformations or return as-is
      resultText = `[Processed with instruction: "${instruction}"] ${inputText.substring(0, 100)}...`;
    }
    
    // Include relevant information from sources if available
    let sourceInfo = '';
    if (retrievedChunks.length > 0) {
      const sourceContent = retrievedChunks[0].text.substring(0, 100);
      sourceInfo = `\n\nReference from knowledge source: "${sourceContent}..."`;
    }
    
    return `Result:\n${resultText}${sourceInfo}`;
  }
}