package llm

import (
	"context"
	"fmt"
	"regexp"
	"silencendo/context"
	"silencendo/ingestion"
	"strings"
)

type MockLLM struct{}

func NewMockLLM() *MockLLM {
	return &MockLLM{}
}

func (m *MockLLM) Generate(ctx context.Context, messages []Message) (string, error) {
	// Mock implementation that creates a response based on the last user message
	var lastUserMessage *Message
	for i := len(messages) - 1; i >= 0; i-- {
		if messages[i].Role == "user" {
			msg := messages[i]
			lastUserMessage = &msg
			break
		}
	}
	
	if lastUserMessage == nil {
		return "I'm a mock LLM. No user message found to respond to.", nil
	}

	// Simple response generation based on keywords
	content := strings.ToLower(lastUserMessage.Content)
	
	if strings.Contains(content, "hello") || strings.Contains(content, "hi") || strings.Contains(content, "hey") {
		return "Hello! I'm your mock AI assistant. How can I help you today?", nil
	} else if strings.Contains(content, "thank") {
		return "You're welcome! Let me know if you need anything else.", nil
	} else if strings.Contains(content, "help") {
		return "I'm here to help! You can ask me questions about your knowledge sources or request text edits.", nil
	} else {
		return fmt.Sprintf("This is a mock response to: \"%s\". In a real implementation, this would be generated by an LLM.", lastUserMessage.Content), nil
	}
}

func (m *MockLLM) Answer(ctx context.Context, question string, retrievedChunks []ingestion.Chunk, context context.ContextType) (string, error) {
	if len(retrievedChunks) == 0 {
		return "In strict mode: No relevant information found in the provided sources to answer this question.", nil
	}

	// Combine all chunk text to analyze
	var fullTextBuilder strings.Builder
	for i, chunk := range retrievedChunks {
		if i > 0 {
			fullTextBuilder.WriteString(" ")
		}
		fullTextBuilder.WriteString(chunk.Text)
	}
	fullText := fullTextBuilder.String()
	
	// For word-specific questions, extract and return actual information
	questionLower := strings.ToLower(question)
	words := strings.Fields(fullText)
	
	if strings.Contains(questionLower, "first word") || (strings.Contains(questionLower, "first") && strings.Contains(questionLower, "word")) {
		if len(words) > 0 {
			return fmt.Sprintf("The first word in the document is \"%s\".", words[0]), nil
		} else {
			return "The document appears to be empty.", nil
		}
	} else if strings.Contains(questionLower, "second word") || (strings.Contains(questionLower, "second") && strings.Contains(questionLower, "word")) {
		if len(words) > 1 {
			return fmt.Sprintf("The second word in the document is \"%s\".", words[1]), nil
		} else {
			return fmt.Sprintf("The document has fewer than 2 words. It contains %d word(s).", len(words)), nil
		}
	} else if strings.Contains(questionLower, "third word") || (strings.Contains(questionLower, "third") && strings.Contains(questionLower, "word")) {
		if len(words) > 2 {
			return fmt.Sprintf("The third word in the document is \"%s\".", words[2]), nil
		} else {
			return fmt.Sprintf("The document has fewer than 3 words. It contains %d word(s).", len(words)), nil
		}
	} else if strings.Contains(questionLower, "word count") || strings.Contains(questionLower, "many words") || strings.Contains(questionLower, "number of words") ||
		(strings.Contains(questionLower, "how many") && strings.Contains(questionLower, "word")) {
		return fmt.Sprintf("The document contains approximately %d words.", len(words)), nil
	} else if strings.Contains(questionLower, "character count") || strings.Contains(questionLower, "many characters") || strings.Contains(questionLower, "number of characters") ||
		(strings.Contains(questionLower, "how many") && strings.Contains(questionLower, "character")) {
		return fmt.Sprintf("The document contains approximately %d characters.", len(fullText)), nil
	} else if strings.Contains(questionLower, "fifth word") || (strings.Contains(questionLower, "fifth") && strings.Contains(questionLower, "word")) {
		if len(words) > 4 {
			return fmt.Sprintf("The fifth word in the document is \"%s\".", words[4]), nil
		} else {
			return fmt.Sprintf("The document has fewer than 5 words. It contains %d word(s).", len(words)), nil
		}
	} else if strings.Contains(questionLower, "15-th word") || strings.Contains(questionLower, "15th word") ||
		(strings.Contains(questionLower, "15") && strings.Contains(questionLower, "word")) {
		if len(words) > 14 {
			return fmt.Sprintf("The 15th word in the document is \"%s\".", words[14]), nil
		} else {
			return fmt.Sprintf("The document has fewer than 15 words. It contains %d word(s).", len(words)), nil
		}
	} else if strings.Contains(questionLower, "what is") && (strings.Contains(questionLower, "document") || strings.Contains(questionLower, "content") || strings.Contains(questionLower, "about")) {
		// Extract main topics from the content
		textLower := strings.ToLower(fullText)
		var topics []string
		
		if strings.Contains(textLower, "artificial intelligence") || strings.Contains(textLower, "ai") {
			topics = append(topics, "Artificial Intelligence")
		}
		if strings.Contains(textLower, "machine learning") {
			topics = append(topics, "Machine Learning")
		}
		if strings.Contains(textLower, "neural network") || strings.Contains(textLower, "neural networks") {
			topics = append(topics, "Neural Networks")
		}
		if strings.Contains(textLower, "natural language processing") || strings.Contains(textLower, "nlp") {
			topics = append(topics, "Natural Language Processing")
		}
		if strings.Contains(textLower, "deep learning") {
			topics = append(topics, "Deep Learning")
		}
		if strings.Contains(textLower, "transform") {
			topics = append(topics, "Industry Transformation")
		}
		
		topicStr := "various AI and technology topics"
		if len(topics) > 0 {
			topicStr = strings.Join(topics, ", ")
		}
		return fmt.Sprintf("This document is about: %s. It discusses how these technologies are transforming industries and their applications.", topicStr), nil
	} else {
		// For other questions, provide a response based on the content
		// In a real implementation with DeepSeek, the LLM would naturally understand and respond to the question
		var relevantContentBuilder strings.Builder
		for i, chunk := range retrievedChunks {
			if i >= 2 {
				break
			}
			if i > 0 {
				relevantContentBuilder.WriteString("\n\n")
			}
			content := chunk.Text
			if len(content) > 200 {
				content = content[:200] + "..."
			}
			relevantContentBuilder.WriteString(content)
		}
		
		return fmt.Sprintf("Based on the provided sources:\n\n%s\n\nAnswer: In a real implementation with an LLM like DeepSeek, the AI would analyze the question \"%s\" and generate a comprehensive response based on the relevant information from the documents.", relevantContentBuilder.String(), question), nil
	}
}

func (m *MockLLM) Edit(ctx context.Context, inputText string, instruction string, retrievedChunks []ingestion.Chunk, context context.ContextType) (string, error) {
	// Apply basic transformations based on the instruction
	resultText := inputText
	instructionLower := strings.ToLower(instruction)
	
	if strings.Contains(instructionLower, "shorter") || strings.Contains(instructionLower, "summarize") || strings.Contains(instructionLower, "reduce") {
		// Simple summarization by taking first and last parts
		words := strings.Fields(inputText)
		if len(words) > 10 {
			var firstHalf []string
			if len(words)/2 > 10 {
				firstHalf = words[:10]
			} else {
				firstHalf = words[:len(words)/2]
			}
			var secondHalf []string
			halfLen := len(words) / 2
			if halfLen > 5 {
				secondHalf = words[len(words)-5:]
			} else {
				secondHalf = words[len(words)-halfLen:]
			}
			resultText = strings.Join(firstHalf, " ") + " [...] " + strings.Join(secondHalf, " ")
		} else {
			var firstFew []string
			if len(words) > 5 {
				firstFew = words[:5]
			} else {
				firstFew = words[:len(words)]
			}
			resultText = strings.Join(firstFew, " ") + " [...]"
		}
	} else if strings.Contains(instructionLower, "longer") || strings.Contains(instructionLower, "expand") {
		resultText = inputText + " [expanded with additional details based on knowledge sources...]"
	} else if strings.Contains(instructionLower, "rewrite") || strings.Contains(instructionLower, "rephrase") {
		words := strings.Fields(inputText)
		for i, j := 0, len(words)-1; i < j; i, j = i+1, j-1 {
			words[i], words[j] = words[j], words[i]
		}
		resultText = "[Rewritten]: " + strings.Join(words, " ") + " [end rewrite]"
	} else if strings.Contains(instructionLower, "fix") || strings.Contains(instructionLower, "grammar") || strings.Contains(instructionLower, "correct") {
		resultText = "[Grammar checked and corrected]: " + inputText + " [corrections applied based on knowledge sources]"
	} else {
		// For other instructions, apply basic transformations or return as-is
		if len(inputText) > 100 {
			resultText = fmt.Sprintf("[Processed with instruction: \"%s\"] %s...", instruction, inputText[:100])
		} else {
			resultText = fmt.Sprintf("[Processed with instruction: \"%s\"] %s", instruction, inputText)
		}
	}
	
	// Include relevant information from sources if available
	sourceInfo := ""
	if len(retrievedChunks) > 0 {
		sourceContent := retrievedChunks[0].Text
		if len(sourceContent) > 100 {
			sourceContent = sourceContent[:100]
		}
		sourceInfo = fmt.Sprintf("\n\nReference from knowledge source: \"%s...\"", sourceContent)
	}
	
	return fmt.Sprintf("Result:\n%s%s", resultText, sourceInfo), nil
}